#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : falcosecurity-libs
Version  : 0.10.5
Release  : 1
URL      : https://github.com/falcosecurity/libs/archive/0.10.5/libs-0.10.5.tar.gz
Source0  : https://github.com/falcosecurity/libs/archive/0.10.5/libs-0.10.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: falcosecurity-libs-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : jq-dev
BuildRequires : libb64-staticdev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(gpr)
BuildRequires : pkgconfig(jsoncpp)
BuildRequires : pkgconfig(libcares)
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(protobuf)
BuildRequires : pkgconfig(re2)
BuildRequires : tbb-dev
BuildRequires : valijson-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Use-C-17.patch

%description
# falcosecurity/libs
[![CI Build](https://github.com/falcosecurity/libs/actions/workflows/ci.yml/badge.svg?branch=master)](https://github.com/falcosecurity/libs/actions/workflows/ci.yml)
[![Architectures](https://img.shields.io/badge/ARCHS-x86__64%7Caarch64%7Cs390x-blueviolet)](#drivers-officially-supported-architectures)

%package dev
Summary: dev components for the falcosecurity-libs package.
Group: Development
Provides: falcosecurity-libs-devel = %{version}-%{release}
Requires: falcosecurity-libs = %{version}-%{release}

%description dev
dev components for the falcosecurity-libs package.


%package license
Summary: license components for the falcosecurity-libs package.
Group: Default

%description license
license components for the falcosecurity-libs package.


%prep
%setup -q -n libs-0.10.5
cd %{_builddir}/libs-0.10.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682099883
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake .. -DCREATE_TEST_TARGETS=OFF \
-DUSE_BUNDLED_DEPS=OFF \
-DUSE_BUNDLED_GTEST=OFF \
-DENABLE_DKMS=OFF \
-DBUILD_LIBSCAP_EXAMPLES=OFF \
-DBUILD_LIBSINSP_EXAMPLES=OFF \
-DUSE_BUNDLED_DRIVER=ON \
-DBUILD_DRIVER=OFF \
-DBUILD_BPF=OFF
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1682099883
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/falcosecurity-libs
cp %{_builddir}/libs-%{version}/COPYING %{buildroot}/usr/share/package-licenses/falcosecurity-libs/eb813b8fdb2276a4454e99623a7eee9507f7fc77 || :
cp %{_builddir}/libs-%{version}/driver/GPL2.txt %{buildroot}/usr/share/package-licenses/falcosecurity-libs/4cc77b90af91e615a64ae04893fdffa7939db84c || :
pushd clr-build
%make_install
popd
## install_append content
# Don't want to install buildable source
rm -rf %{buildroot}/usr/src/scap-0.0.0
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/falcosecurity/driver/driver_config.h
/usr/include/falcosecurity/driver/feature_gates.h
/usr/include/falcosecurity/driver/kernel_hacks.h
/usr/include/falcosecurity/driver/ppm.h
/usr/include/falcosecurity/driver/ppm_api_version.h
/usr/include/falcosecurity/driver/ppm_compat_unistd_32.h
/usr/include/falcosecurity/driver/ppm_events.h
/usr/include/falcosecurity/driver/ppm_events_public.h
/usr/include/falcosecurity/driver/ppm_fillers.h
/usr/include/falcosecurity/driver/ppm_flag_helpers.h
/usr/include/falcosecurity/driver/ppm_ringbuffer.h
/usr/include/falcosecurity/driver/ppm_syscall.h
/usr/include/falcosecurity/driver/ppm_tp.h
/usr/include/falcosecurity/driver/ppm_version.h
/usr/include/falcosecurity/driver/systype_compat.h
/usr/include/falcosecurity/userspace/common/common_config.h
/usr/include/falcosecurity/userspace/common/strlcpy.h
/usr/include/falcosecurity/userspace/common/types.h
/usr/include/falcosecurity/userspace/libscap/compat/bpf.h
/usr/include/falcosecurity/userspace/libscap/compat/bpf_common.h
/usr/include/falcosecurity/userspace/libscap/compat/misc.h
/usr/include/falcosecurity/userspace/libscap/compat/perf_event.h
/usr/include/falcosecurity/userspace/libscap/engine/bpf/bpf.h
/usr/include/falcosecurity/userspace/libscap/engine/bpf/bpf_public.h
/usr/include/falcosecurity/userspace/libscap/engine/bpf/scap_bpf.h
/usr/include/falcosecurity/userspace/libscap/engine/gvisor/gvisor.h
/usr/include/falcosecurity/userspace/libscap/engine/gvisor/gvisor_public.h
/usr/include/falcosecurity/userspace/libscap/engine/gvisor/parsers.h
/usr/include/falcosecurity/userspace/libscap/engine/kmod/kmod.h
/usr/include/falcosecurity/userspace/libscap/engine/kmod/kmod_public.h
/usr/include/falcosecurity/userspace/libscap/engine/modern_bpf/modern_bpf_public.h
/usr/include/falcosecurity/userspace/libscap/engine/modern_bpf/scap_modern_bpf.h
/usr/include/falcosecurity/userspace/libscap/engine/nodriver/nodriver.h
/usr/include/falcosecurity/userspace/libscap/engine/nodriver/nodriver_public.h
/usr/include/falcosecurity/userspace/libscap/engine/noop/noop.h
/usr/include/falcosecurity/userspace/libscap/engine/savefile/savefile.h
/usr/include/falcosecurity/userspace/libscap/engine/savefile/savefile_public.h
/usr/include/falcosecurity/userspace/libscap/engine/savefile/scap_reader.h
/usr/include/falcosecurity/userspace/libscap/engine/source_plugin/source_plugin.h
/usr/include/falcosecurity/userspace/libscap/engine/source_plugin/source_plugin_public.h
/usr/include/falcosecurity/userspace/libscap/engine/test_input/test_input_public.h
/usr/include/falcosecurity/userspace/libscap/engine/udig/udig.h
/usr/include/falcosecurity/userspace/libscap/engine/udig/udig_public.h
/usr/include/falcosecurity/userspace/libscap/engine_handle.h
/usr/include/falcosecurity/userspace/libscap/linux/barrier.h
/usr/include/falcosecurity/userspace/libscap/linux/gettimeofday.h
/usr/include/falcosecurity/userspace/libscap/linux/scap_linux_int.h
/usr/include/falcosecurity/userspace/libscap/linux/sleep.h
/usr/include/falcosecurity/userspace/libscap/linux/unixid.h
/usr/include/falcosecurity/userspace/libscap/macos/barrier.h
/usr/include/falcosecurity/userspace/libscap/macos/gettimeofday.h
/usr/include/falcosecurity/userspace/libscap/macos/sleep.h
/usr/include/falcosecurity/userspace/libscap/plugin_info.h
/usr/include/falcosecurity/userspace/libscap/ringbuffer/devset.h
/usr/include/falcosecurity/userspace/libscap/ringbuffer/ringbuffer.h
/usr/include/falcosecurity/userspace/libscap/scap-int.h
/usr/include/falcosecurity/userspace/libscap/scap.h
/usr/include/falcosecurity/userspace/libscap/scap_assert.h
/usr/include/falcosecurity/userspace/libscap/scap_const.h
/usr/include/falcosecurity/userspace/libscap/scap_engine_util.h
/usr/include/falcosecurity/userspace/libscap/scap_engines.h
/usr/include/falcosecurity/userspace/libscap/scap_limits.h
/usr/include/falcosecurity/userspace/libscap/scap_open.h
/usr/include/falcosecurity/userspace/libscap/scap_procs.h
/usr/include/falcosecurity/userspace/libscap/scap_savefile.h
/usr/include/falcosecurity/userspace/libscap/scap_suppress.h
/usr/include/falcosecurity/userspace/libscap/scap_test.h
/usr/include/falcosecurity/userspace/libscap/scap_vtable.h
/usr/include/falcosecurity/userspace/libscap/scap_zlib.h
/usr/include/falcosecurity/userspace/libscap/settings.h
/usr/include/falcosecurity/userspace/libscap/stdint_win.h
/usr/include/falcosecurity/userspace/libscap/strerror.h
/usr/include/falcosecurity/userspace/libscap/userspace_flag_helpers.h
/usr/include/falcosecurity/userspace/libscap/uthash.h
/usr/include/falcosecurity/userspace/libscap/win32/barrier.h
/usr/include/falcosecurity/userspace/libscap/win32/gettimeofday.h
/usr/include/falcosecurity/userspace/libscap/win32/sleep.h
/usr/include/falcosecurity/userspace/libsinsp/addrinfo.h
/usr/include/falcosecurity/userspace/libsinsp/async/async_key_value_source.h
/usr/include/falcosecurity/userspace/libsinsp/capture_stats_source.h
/usr/include/falcosecurity/userspace/libsinsp/cgroup_limits.h
/usr/include/falcosecurity/userspace/libsinsp/cgroup_list_counter.h
/usr/include/falcosecurity/userspace/libsinsp/container.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/bpm.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/container_async_source.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/container_cache_interface.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/container_engine_base.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/cri.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/docker/async_source.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/docker/base.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/docker/connection.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/docker/docker_linux.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/docker/lookup_request.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/docker/podman.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/libvirt_lxc.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/lxc.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/mesos.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/rkt.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/sinsp_container_type.h
/usr/include/falcosecurity/userspace/libsinsp/container_engine/static_container.h
/usr/include/falcosecurity/userspace/libsinsp/container_info.h
/usr/include/falcosecurity/userspace/libsinsp/cri.h
/usr/include/falcosecurity/userspace/libsinsp/cyclewriter.h
/usr/include/falcosecurity/userspace/libsinsp/dns_manager.h
/usr/include/falcosecurity/userspace/libsinsp/dumper.h
/usr/include/falcosecurity/userspace/libsinsp/event.h
/usr/include/falcosecurity/userspace/libsinsp/eventformatter.h
/usr/include/falcosecurity/userspace/libsinsp/fdinfo.h
/usr/include/falcosecurity/userspace/libsinsp/fields_info.h
/usr/include/falcosecurity/userspace/libsinsp/filter.h
/usr/include/falcosecurity/userspace/libsinsp/filter/ast.h
/usr/include/falcosecurity/userspace/libsinsp/filter/escaping.h
/usr/include/falcosecurity/userspace/libsinsp/filter/parser.h
/usr/include/falcosecurity/userspace/libsinsp/filter_check_list.h
/usr/include/falcosecurity/userspace/libsinsp/filter_value.h
/usr/include/falcosecurity/userspace/libsinsp/filterchecks.h
/usr/include/falcosecurity/userspace/libsinsp/gen_filter.h
/usr/include/falcosecurity/userspace/libsinsp/grpc_channel_registry.h
/usr/include/falcosecurity/userspace/libsinsp/gvisor_config.h
/usr/include/falcosecurity/userspace/libsinsp/http_parser.h
/usr/include/falcosecurity/userspace/libsinsp/http_reason.h
/usr/include/falcosecurity/userspace/libsinsp/ifinfo.h
/usr/include/falcosecurity/userspace/libsinsp/include/sinsp_external_processor.h
/usr/include/falcosecurity/userspace/libsinsp/internal_metrics.h
/usr/include/falcosecurity/userspace/libsinsp/json_error_log.h
/usr/include/falcosecurity/userspace/libsinsp/json_query.h
/usr/include/falcosecurity/userspace/libsinsp/k8s.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_api_error.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_api_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_component.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_daemonset_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_deployment_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_dispatcher.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_event_data.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_event_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_namespace_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_net.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_node_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_pod_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_replicaset_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_replicationcontroller_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_service_handler.h
/usr/include/falcosecurity/userspace/libsinsp/k8s_state.h
/usr/include/falcosecurity/userspace/libsinsp/logger.h
/usr/include/falcosecurity/userspace/libsinsp/marathon_component.h
/usr/include/falcosecurity/userspace/libsinsp/marathon_http.h
/usr/include/falcosecurity/userspace/libsinsp/mesos.h
/usr/include/falcosecurity/userspace/libsinsp/mesos_auth.h
/usr/include/falcosecurity/userspace/libsinsp/mesos_collector.h
/usr/include/falcosecurity/userspace/libsinsp/mesos_common.h
/usr/include/falcosecurity/userspace/libsinsp/mesos_component.h
/usr/include/falcosecurity/userspace/libsinsp/mesos_http.h
/usr/include/falcosecurity/userspace/libsinsp/mesos_state.h
/usr/include/falcosecurity/userspace/libsinsp/mutex.h
/usr/include/falcosecurity/userspace/libsinsp/parsers.h
/usr/include/falcosecurity/userspace/libsinsp/plugin.h
/usr/include/falcosecurity/userspace/libsinsp/plugin_filtercheck.h
/usr/include/falcosecurity/userspace/libsinsp/plugin_manager.h
/usr/include/falcosecurity/userspace/libsinsp/prefix_search.h
/usr/include/falcosecurity/userspace/libsinsp/procfs_utils.h
/usr/include/falcosecurity/userspace/libsinsp/protodecoder.h
/usr/include/falcosecurity/userspace/libsinsp/runc.h
/usr/include/falcosecurity/userspace/libsinsp/scap_open_exception.h
/usr/include/falcosecurity/userspace/libsinsp/settings.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_auth.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_curl.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_errno.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_exception.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_inet.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_int.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_pd_callback_type.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_public.h
/usr/include/falcosecurity/userspace/libsinsp/sinsp_signal.h
/usr/include/falcosecurity/userspace/libsinsp/socket_collector.h
/usr/include/falcosecurity/userspace/libsinsp/socket_handler.h
/usr/include/falcosecurity/userspace/libsinsp/stats.h
/usr/include/falcosecurity/userspace/libsinsp/stopwatch.h
/usr/include/falcosecurity/userspace/libsinsp/third-party/jsoncpp/json/json-forwards.h
/usr/include/falcosecurity/userspace/libsinsp/third-party/jsoncpp/json/json.h
/usr/include/falcosecurity/userspace/libsinsp/third-party/tinydir.h
/usr/include/falcosecurity/userspace/libsinsp/threadinfo.h
/usr/include/falcosecurity/userspace/libsinsp/token_bucket.h
/usr/include/falcosecurity/userspace/libsinsp/tracer_emitter.h
/usr/include/falcosecurity/userspace/libsinsp/tracers.h
/usr/include/falcosecurity/userspace/libsinsp/tuples.h
/usr/include/falcosecurity/userspace/libsinsp/uri.h
/usr/include/falcosecurity/userspace/libsinsp/uri_parser.h
/usr/include/falcosecurity/userspace/libsinsp/user.h
/usr/include/falcosecurity/userspace/libsinsp/user_event.h
/usr/include/falcosecurity/userspace/libsinsp/user_event_logger.h
/usr/include/falcosecurity/userspace/libsinsp/utils.h
/usr/include/falcosecurity/userspace/libsinsp/value_parser.h
/usr/include/falcosecurity/userspace/libsinsp/version.h
/usr/include/falcosecurity/userspace/plugin/plugin_api.h
/usr/include/falcosecurity/userspace/plugin/plugin_loader.h
/usr/include/falcosecurity/userspace/plugin/plugin_types.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/falcosecurity-libs/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/falcosecurity-libs/eb813b8fdb2276a4454e99623a7eee9507f7fc77
